#!/usr/bin/with-contenv bash
su-exec "${UNAME}" xpra $XPRA_MODE $DISPLAY\
  --bind-tcp="0.0.0.0:${XPRA_TCP_PORT}"\
  --compress="${XPRA_COMPRESS}"\
  --dpi="${XPRA_DPI}"\
  --encoding="${XPRA_ENCODING}"\
  --html="${XPRA_HTML}"\
  --keyboard-sync="${XPRA_KEYBOARD_SYNC}"\
  --microphone=disabled\
  --mmap="${XPRA_MMAP}"\
  --no-daemon\
  --printing=no\
  --pulseaudio=no\
  --readonly="${XPRA_READONLY}"\
  --sharing="${XPRA_SHARING}"\
  --speaker=disabled\
  --notifications=no\
  --clipboard=yes\
  --system-tray=no